language: python

## Use the default python version on macOS
#python:

os:
  - linux
  ## We can't add macOS here, because language: python isn't supported by
  ## macOS Travis. So we add macOS in matrix: include:

## The build matrix in the following stanza expands into builds for each
## OS and python version.
## Placeholder
#env:
#  global:
#    -
#  matrix:
#    -

matrix:
  # include creates Linux, python 2.7, tor stable builds by default
  include:
    ## Test macOS with its default python version, and work around an issue
    ## with language: python on Travis macOS
    - os: osx
      language: c
    ## Test tor 0.3.5 and tor nightly
    - addons:
        apt:
          sources:
            - sourceline: 'deb https://deb.torproject.org/torproject.org trusty main'
              key_url: 'http://ha.pool.sks-keyservers.net/pks/lookup?search=0xA3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&options=mr&op=get'
            - sourceline: 'deb https://deb.torproject.org/torproject.org tor-experimental-0.3.5.x-trusty main'
          packages:
            - tor
    - addons:
        apt:
          sources:
            - sourceline: 'deb https://deb.torproject.org/torproject.org trusty main'
              key_url: 'http://ha.pool.sks-keyservers.net/pks/lookup?search=0xA3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&options=mr&op=get'
            - sourceline: 'deb https://deb.torproject.org/torproject.org tor-nightly-master-trusty main'
          packages:
            - tor
    ## Test all supported python releases
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    ## Travis Trusty doesn't support these versions
    #- python: "3.7"
    #- python: "3.8-dev"
    - python: "nightly"
    # PyPy versions
    ## Travis Trusty doesn't support these versions
    #- python: "pypy2.7"
    - python: "pypy3.5"

  ## Uncomment to allow the build to report success (with non-required
  ## sub-builds continuing to run) if all required sub-builds have
  ## succeeded.  This is somewhat buggy currently: it can cause
  ## duplicate notifications and prematurely report success if a
  ## single sub-build has succeeded.  See
  ## https://github.com/travis-ci/travis-ci/issues/1696
  #fast_finish: true

  ## Careful! We use global envs, which makes it hard to exclude or
  ## allow failures by env:
  ## https://docs.travis-ci.com/user/customizing-the-build#matching-jobs-with-allow_failures
  #exclude:
    ## Placeholder
    #- python: "3.6"
    #  os: linux

## We don't need sudo. (The "apt:" stanza after this allows us to not need
## sudo; otherwise, we would need it for getting dependencies.)
sudo: false

## (Linux only) Use the latest Linux image (Ubuntu Trusty)
dist: trusty

## (OSX only) Use the default OSX image
## See https://docs.travis-ci.com/user/reference/osx#os-x-version
## Default is Xcode 9.4 on macOS 10.13 as of August 2018
#osx_image: xcode9.4

## Download our dependencies
addons:
  ## (Linux only)
  apt:
    sources:
      ## Trusty has Tor 0.2.4, so we need a newer version of Tor from the
      ## torproject repositories, and the torproject key from the keyservers
      - sourceline: 'deb https://deb.torproject.org/torproject.org trusty main'
        key_url: 'http://ha.pool.sks-keyservers.net/pks/lookup?search=0xA3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&options=mr&op=get'
    packages:
      ## Required dependencies
      - tor
      ## Is this necessary for a once-off build?
      #- deb.torproject.org-keyring
  ## (macOS only)
  homebrew:
    packages:
      ## Required dependencies
      - tor

before_install:
  ## Placeholder
  -

install:
  ## Placeholder
  -
  ##
  ## Finally, list installed package versions
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dpkg-query --show; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list --versions; fi
  - python --version
  - tor --version

script:
  - tools/test-network.sh

after_failure:
  ## Re-run chutney in debug mode
  ## TODO: improve debug mode
  - tools/test-network.sh --debug

after_success:
  ## Placeholder
  -

notifications:
  irc:
    channels:
      - "irc.oftc.net#tor-ci"
    template:
      - "%{repository} %{branch} %{commit} - %{author}: %{commit_subject}"
      - "Build #%{build_number} %{result}. Details: %{build_url}"
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: change
